=== CosmicDNS/PHP-DNS-SERVER/php-dns-server.xsd
<xs:schema elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="domain">
        <xs:complexType>
            <xs:sequence>
                <xs:element type="xs:string" name="name"/>
                <xs:element type="xs:short" name="default-ttl"/>
                <xs:element name="resource-records">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="resource-record" maxOccurs="unbounded" minOccurs="0">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element type="xs:string" name="name" minOccurs="0"/>
                                        <xs:element type="xs:short" name="ttl" minOccurs="0"/>
                                        <xs:element type="xs:string" name="type"/>
                                        <xs:element type="xs:string" name="class" minOccurs="0"/>
                                        <xs:element name="rdata">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element type="xs:string" name="mname" minOccurs="0"/>
                                                    <xs:element type="xs:string" name="rname" minOccurs="0"/>
                                                    <xs:element type="xs:byte" name="serial" minOccurs="0"/>
                                                    <xs:element type="xs:short" name="refresh" minOccurs="0"/>
                                                    <xs:element type="xs:short" name="retry" minOccurs="0"/>
                                                    <xs:element type="xs:short" name="expire" minOccurs="0"/>
                                                    <xs:element type="xs:short" name="minimum" minOccurs="0"/>
                                                    <xs:element type="xs:string" name="address" minOccurs="0"/>
                                                    <xs:element type="xs:string" name="target" minOccurs="0"/>
                                                    <xs:element type="xs:byte" name="preference" minOccurs="0"/>
                                                    <xs:element type="xs:string" name="exchange" minOccurs="0"/>
                                                    <xs:element type="xs:string" name="text" minOccurs="0"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== CosmicDNS/PHP-DNS-SERVER/src/Tests/Resources/example.com.xml
<?xml version="1.0" encoding="UTF-8"?>
<domain
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="../../../php-dns-server.xsd"
>
    <name>example.com.</name>
    <default-ttl>7200</default-ttl>

    <resource-records>
        <resource-record>
            <name>@</name>
            <ttl>10800</ttl>
            <type>SOA</type>
            <class>IN</class>
            <rdata>
                <mname>example.com.</mname>
                <rname>postmaster</rname>
                <serial>2</serial>
                <refresh>3600</refresh>
                <retry>7200</retry>
                <expire>10800</expire>
                <minimum>3600</minimum>
            </rdata>
        </resource-record>

        <resource-record>
            <type>A</type>
            <rdata>
                <address>12.34.56.78</address>
            </rdata>
        </resource-record>

        <resource-record>
            <type>A</type>
            <rdata>
                <address>90.12.34.56</address>
            </rdata>
        </resource-record>

        <resource-record>
            <type>AAAA</type>
            <rdata>
                <address>2001:acad:ad::32</address>
            </rdata>
        </resource-record>

        <resource-record>
            <name>www</name>
            <type>cname</type>
            <rdata>
                <target>@</target>
            </rdata>
        </resource-record>

        <resource-record>
            <name>ldap</name>
            <type>A</type>
            <rdata>
                <address>192.168.3.89</address>
            </rdata>
        </resource-record>

        <resource-record>
            <name>@</name>
            <type>MX</type>
            <rdata>
                <preference>15</preference>
                <exchange>mail</exchange>
            </rdata>
        </resource-record>

        <resource-record>
            <name>*.subdomain</name>
            <type>A</type>
            <rdata>
                <address>192.168.1.42</address>
            </rdata>
        </resource-record>

        <resource-record>
            <name>_ldap._tcp</name>
            <type>SRV</type>
            <rdata>
                <priority>1</priority>
                <weight>5</weight>
                <port>389</port>
                <target>ldap</target>
            </rdata>
        </resource-record>
    </resource-records>
</domain>

=== CosmicDNS/PHP-DNS-SERVER/tests/Resources/test.com.xml
<?xml version="1.0" encoding="UTF-8"?>
<domain
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="http://example.com/php-dns-server.xsd"
>
    <name>test.com.</name>
    <default-ttl>7200</default-ttl>

    <resource-records>
        <resource-record>
            <name>@</name>
            <ttl>10800</ttl>
            <type>SOA</type>
            <class>IN</class>
            <rdata>
                <mname>ns1</mname>
                <rname>admin</rname>
                <serial>2014111100</serial>
                <refresh>1800</refresh>
                <retry>7200</retry>
                <expire>8600</expire>
                <minimum>300</minimum>
            </rdata>
        </resource-record>

        <resource-record>
            <type>A</type>
            <rdata>
                <address>111.111.111.111</address>
            </rdata>
        </resource-record>

        <resource-record>
            <type>AAAA</type>
            <rdata>
                <address>DEAD:01::BEEF</address>
            </rdata>
        </resource-record>

        <resource-record>
            <name>@</name>
            <type>NS</type>
            <rdata>
                <target>ns1</target>
            </rdata>
        </resource-record>

        <resource-record>
            <name>@</name>
            <type>NS</type>
            <rdata>
                <target>ns2</target>
            </rdata>
        </resource-record>

        <resource-record>
            <name>ns1</name>
            <type>A</type>
            <rdata>
                <address>15.15.12.10</address>
            </rdata>
        </resource-record>

        <resource-record>
            <name>ns2</name>
            <type>A</type>
            <rdata>
                <address>15.15.12.20</address>
            </rdata>
        </resource-record>

        <resource-record>
            <name>@</name>
            <type>cname</type>
            <rdata>
                <target>ww2</target>
            </rdata>
        </resource-record>

        <resource-record>
            <type>MX</type>
            <rdata>
                <preference>10</preference>
                <exchange>mail-gw1</exchange>
            </rdata>
        </resource-record>

        <resource-record>
            <type>MX</type>
            <rdata>
                <preference>20</preference>
                <exchange>mail-gw2</exchange>
            </rdata>
        </resource-record>

        <resource-record>
            <type>TXT</type>
            <rdata>
                <text>Some text.</text>
            </rdata>
        </resource-record>
    </resource-records>
</domain>

=== CosmicDNS/PHP-DNS-SERVER/src/Tests/Resources/test2.com.xml
<?xml version="1.0" encoding="UTF-8"?>
<domain
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="../../../php-dns-server.xsd"
>
    <name>test2.com.</name>
    <default-ttl>300</default-ttl>

    <resource-records>
        <resource-record>
            <name>@</name>
            <ttl>10800</ttl>
            <type>SOA</type>
            <class>IN</class>
            <rdata>
                <mname>ns1</mname>
                <rname>admin</rname>
                <serial>2014111100</serial>
                <refresh>1800</refresh>
                <retry>7200</retry>
                <expire>8600</expire>
                <minimum>300</minimum>
            </rdata>
        </resource-record>

        <resource-record>
            <type>A</type>
            <rdata>
                <address>111.111.111.111</address>
            </rdata>
        </resource-record>

        <resource-record>
            <type>A</type>
            <rdata>
                <address>112.112.112.112</address>
            </rdata>
        </resource-record>

        <resource-record>
            <type>MX</type>
            <rdata>
                <preference>20</preference>
                <exchange>mail-gw1</exchange>
            </rdata>
        </resource-record>

        <resource-record>
            <type>MX</type>
            <rdata>
                <preference>30</preference>
                <exchange>mail-gw2</exchange>
            </rdata>
        </resource-record>

        <resource-record>
            <type>TXT</type>
            <rdata>
                <text>Some text.</text>
            </rdata>
        </resource-record>
    </resource-records>
</domain>
